[package]
name = "materials"
version = "0.1.0"
edition = "2021"

[dependencies]
renderer.workspace = true
anyhow.workspace = true
nalgebra-glm.workspace = true
imgui.workspace = true
serde.workspace = true
serde_json.workspace = true
learnopengl-utils.workspace = true
