[package]
name = "shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
renderer.workspace = true
anyhow.workspace = true
nalgebra-glm.workspace = true
learnopengl-utils.workspace = true
