[package]
name = "renderer"
description = "Some simple renderer library with utilities"
repository = "https://github.com/platc2/opengl-rust"
keywords = ["OpenGL", "Rust"]
version = "0.1.0"
edition = "2021"

[features]
default = ["imgui"]
imgui = ["dep:imgui"]

[dependencies]
imgui = { workspace = true, optional = true }
gl_bindings = { workspace = true, features = ["GL45", "struct"] }
opengl-rs = { workspace = true, features = ["GL45"] }
sdl2.workspace = true
anyhow.workspace = true
nalgebra-glm.workspace = true
stb_image.workspace = true
thiserror.workspace = true

[package.metadata.vcpkg]
dependencies = ["sdl2"]
git = "https://github.com/microsoft/vcpkg"
rev = "2025.09.17"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
